In [2]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images")

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [3]:
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
X.shape

(100, 1)

In [4]:
X_b = np.c_[np.ones((100, 1)), X]

In [5]:
X_b

array([[ 1.        ,  0.74908024],
       [ 1.        ,  1.90142861],
       [ 1.        ,  1.46398788],
       [ 1.        ,  1.19731697],
       [ 1.        ,  0.31203728],
       [ 1.        ,  0.31198904],
       [ 1.        ,  0.11616722],
       [ 1.        ,  1.73235229],
       [ 1.        ,  1.20223002],
       [ 1.        ,  1.41614516],
       [ 1.        ,  0.04116899],
       [ 1.        ,  1.9398197 ],
       [ 1.        ,  1.66488528],
       [ 1.        ,  0.42467822],
       [ 1.        ,  0.36364993],
       [ 1.        ,  0.36680902],
       [ 1.        ,  0.60848449],
       [ 1.        ,  1.04951286],
       [ 1.        ,  0.86389004],
       [ 1.        ,  0.58245828],
       [ 1.        ,  1.22370579],
       [ 1.        ,  0.27898772],
       [ 1.        ,  0.5842893 ],
       [ 1.        ,  0.73272369],
       [ 1.        ,  0.91213997],
       [ 1.        ,  1.57035192],
       [ 1.        ,  0.39934756],
       [ 1.        ,  1.02846888],
       [ 1.        ,

In [6]:
X_new = np.array([[0], [2]])
X_new

array([[0],
       [2]])

In [7]:
X_new_b = np.c_[np.ones((2, 1)), X_new]
X_new_b

array([[ 1.,  0.],
       [ 1.,  2.]])

In [10]:
m = len(X_b)
np.random.seed(42)
random_index = np.random.randint(m)
random_index

51

In [15]:
X_b

array([[ 1.        ,  0.74908024],
       [ 1.        ,  1.90142861],
       [ 1.        ,  1.46398788],
       [ 1.        ,  1.19731697],
       [ 1.        ,  0.31203728],
       [ 1.        ,  0.31198904],
       [ 1.        ,  0.11616722],
       [ 1.        ,  1.73235229],
       [ 1.        ,  1.20223002],
       [ 1.        ,  1.41614516],
       [ 1.        ,  0.04116899],
       [ 1.        ,  1.9398197 ],
       [ 1.        ,  1.66488528],
       [ 1.        ,  0.42467822],
       [ 1.        ,  0.36364993],
       [ 1.        ,  0.36680902],
       [ 1.        ,  0.60848449],
       [ 1.        ,  1.04951286],
       [ 1.        ,  0.86389004],
       [ 1.        ,  0.58245828],
       [ 1.        ,  1.22370579],
       [ 1.        ,  0.27898772],
       [ 1.        ,  0.5842893 ],
       [ 1.        ,  0.73272369],
       [ 1.        ,  0.91213997],
       [ 1.        ,  1.57035192],
       [ 1.        ,  0.39934756],
       [ 1.        ,  1.02846888],
       [ 1.        ,